#!/usr/bin/env bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# Create symlinks for existing configurations
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf


# TODO: Fetch and set up Zsh configuration files from my main dotfiles repo
# curl -o "$HOME/.zshrc" https://raw.githubusercontent.com/lkdm/dotfiles/main/.zshrc
# curl -o "$HOME/.zprofile" https://raw.githubusercontent.com/lkdm/dotfiles/main/.zprofile

Use brew to install packages
packages=(
  ripgrep
  npm
  lazygit
  fzf
  direnv
)

for package in "${packages[@]}"; do
  echo "Installing $package..."
  /home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

echo "All packages have been installed."

# TODO: Setup completions

echo "Setup complete. Zsh configuration files have been downloaded and set up."
